build:
    image: golang:1.9
    tags:
    - ci-kubernetes
    script:
    - pkg=github.com/mcluseau/kgate
    - mkdir -p /go/src/$(dirname $pkg)
    - ln -s $PWD /go/src/$pkg
    - cd $pkg
    - mkdir dist
    - for os in linux windows darwin; do
        mkdir dist/$os
        cd dist/$os
        go build $pkg
      done
    artefacts:
      paths:
      - dist
