build:
    image: golang:1.9
    tags:
    - ci-kubernetes
    script:
    - pkg=github.com/mcluseau/kgate
    - mkdir -p /go/src/$(dirname $pkg)
    - ln -s $PWD /go/src/$pkg
    - cd /go/src/$pkg
    - mkdir dist
    - |
      set -ex
      for os in linux windows darwin; do
        mkdir dist/$os
        cd dist/$os
        GOOS=$os go build $pkg
        cd -
      done
    - cd dist/linux && go build $pkg/cmd/kgatectl
    artifacts:
      paths:
      - dist
